name: Build and Publish to Docker Hub

env:
  VERSION: 22.04

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build-and-publish-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Get metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.repository }}
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}},prefix=${{ env.VERSION }}
            type=semver,pattern={{major}}.{{minor}},prefix=${{ env.VERSION }}
            type=raw,value=main,enable={{is_default_branch}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      -
        name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
