name: 'On Push Dockerfile'

env:
  TAGS: 1.79.0,1.79

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  on-push-dockerfile:
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Checkout repository'
        uses: actions/checkout@v4
      -
        name: 'Build and push image'
        uses: rtvu/build-and-push-to-docker-hub-action@v2.0.0
        with:
          image: ${{ github.repository }}
          latest: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAGS }}
          token: ${{ secrets.DOCKER_HUB_TOKEN }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
